import * as THREE from 'three';
import {createMantaModel} from '../creatures/manta/index.ts';
import {createWhaleSharkModel} from '../creatures/whale-shark/index.ts';
import {ArcadeAnimalMotion} from '../places/last-arcade/biology/Motion.ts';
import {prepareLastArcade} from '../places/last-arcade/index.ts';
import {createChromisVisuals,setChromisMotion} from '../creatures/chromis/index.ts';
import {createFusilierVisuals,setFusilierMotion} from '../creatures/fusilier/index.ts';
import {createArcadeSchools} from '../systems/schooling/index.ts';
import {arcadeObstacles} from '../places/last-arcade/biology/Obstacles.ts';
import {sampleTime} from '../systems/TimeOfDay.ts';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.08;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
$('stage').append(renderer.domElement);const camera=new THREE.PerspectiveCamera(42,1,.02,700),scene=new THREE.Scene();scene.background=new THREE.Color('#58676e');
const orthographic=new THREE.OrthographicCamera(-4,4,4,-4,.02,700);
const hemi=new THREE.HemisphereLight('#dae7f2','#8e887b',1.3),key=new THREE.DirectionalLight('#fff1d9',3);key.position.set(5,8,7);scene.add(hemi,key);
const models=[createMantaModel(5.8,9101),createMantaModel(5.4,9102),createMantaModel(5.1,9103),createWhaleSharkModel(8.5,9140)];models.forEach(m=>scene.add(m.root));
const smallModels=[createChromisVisuals(1,new Float32Array([0]),new Float32Array([.045])),createFusilierVisuals(1,new Float32Array([0]),new Float32Array([.24]))];smallModels.forEach(m=>scene.add(m.root));
let schoolReview=createArcadeSchools({seed:91626,obstacles:arcadeObstacles()});scene.add(schoolReview.root);
const gray=new THREE.MeshStandardMaterial({color:'#afb5b5',roughness:.7,side:THREE.DoubleSide});let motion=new ArcadeAnimalMotion(),elapsed=0,last=performance.now(),playing=false,raf=0,street:Awaited<ReturnType<typeof prepareLastArcade>> extends (...args:any)=>infer R?R:never;
let streetScene:THREE.Scene|undefined,loading=false;const samples:any[]=[];let nextSample=0,soakStart=0,soakRunning=false,recorder:MediaRecorder|undefined,recordChunks:BlobPart[]=[],recordStopped=false;
const composite=document.createElement('canvas'),ctx=composite.getContext('2d')!;let captureStream:MediaStream|undefined;let frameMs:number[]=[];
function download(name:string,blob:Blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.textContent=name;$('downloads').append(a);}
function resize(){const stage=$('stage');renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
async function select(){const subject=$<HTMLSelectElement>('subject').value;if(subject==='street'&&!streetScene&&!loading){loading=true;$('status').textContent='載入商店街';streetScene=new THREE.Scene();street=(await prepareLastArcade())(streetScene,renderer);loading=false;}$('status').textContent='已就緒';draw(0);}
function draw(dt:number){
 const isStreet=$<HTMLSelectElement>('subject').value==='street',isSchools=$<HTMLSelectElement>('subject').value==='schools',view=$<HTMLSelectElement>('view').value;
 schoolReview.root.visible=isSchools;
 if(isSchools){models.forEach(m=>m.root.visible=false);smallModels.forEach(m=>m.root.visible=false);schoolReview.update(dt,elapsed);camera.fov=42;camera.up.set(0,1,0);camera.position.set(12,3,-5);camera.lookAt(5.7,1.5,-11);camera.updateProjectionMatrix();scene.overrideMaterial=null;renderer.render(scene,camera);}
 else if(isStreet&&streetScene&&street){camera.fov=street.fov??62;camera.position.set(...street.position);camera.lookAt(...street.target);camera.updateProjectionMatrix();street.update(dt,elapsed,{...sampleTime(14),lowQuality:false});renderer.render(streetScene,camera);}
 else{const subject=$<HTMLSelectElement>('subject').value,small=subject==='chromis'?0:subject==='fusilier'?1:-1;smallModels.forEach((m,i)=>m.root.visible=i===small);const index=$<HTMLSelectElement>('subject').value==='whale'?3:$<HTMLSelectElement>('subject').value==='manta-b'?1:$<HTMLSelectElement>('subject').value==='manta-c'?2:0;models.forEach((m,i)=>m.root.visible=small<0&&i===index);const states=motion.sample(elapsed),s=states[index];const neutral=$<HTMLInputElement>('neutral').checked;models[index].update({phase:s.phase,amplitude:neutral?0:1,glide:neutral?0:s.glide,asymmetry:neutral?0:s.asymmetry});
 if(small>=0){if(small===0)setChromisMotion(smallModels[0],0,elapsed*3,1);else setFusilierMotion(smallModels[1],0,elapsed*4,1.6);smallModels[small].update(elapsed);}
 camera.fov=42;const d=small===0?.10:small===1?.55:index===3?12:9,at=new THREE.Vector3(0,0,small>=0||index===3?0:-.95);
 camera.up.set(0,1,0);if(view==='top'){camera.position.set(.01,d,at.z);camera.up.set(0,0,1);}else if(view==='bottom'){camera.position.set(.01,-d,at.z);camera.up.set(0,0,1);}else if(view==='side')camera.position.set(d,0,at.z);else if(view==='front')camera.position.set(0,0,d);else if(view==='head'){at.set(0,0,index===3?2.8:1);camera.position.set(d*.10,d*.08,d*.39);}else camera.position.set(d*.58,d*.42,d*.55);camera.lookAt(at);camera.updateProjectionMatrix();scene.overrideMaterial=$<HTMLInputElement>('gray').checked?gray:null;let reviewCamera:THREE.Camera=camera;if($<HTMLInputElement>('ortho').checked){const halfHeight=(view==='head'?d*.11:d*.35)*Math.max(1,1/camera.aspect);orthographic.left=-halfHeight*camera.aspect;orthographic.right=halfHeight*camera.aspect;orthographic.top=halfHeight;orthographic.bottom=-halfHeight;orthographic.position.copy(camera.position);orthographic.quaternion.copy(camera.quaternion);orthographic.updateProjectionMatrix();reviewCamera=orthographic;}renderer.render(scene,reviewCamera);}
 camera.updateProjectionMatrix();
 const biology=streetScene?.getObjectByName('kuroshio-arcade-biology');const debug=isSchools?{schools:schoolReview.getDebug()}:isStreet&&biology?.userData.getDebug?biology.userData.getDebug():motion.debug();
 $('debug').textContent=JSON.stringify({elapsed:Number(elapsed.toFixed(2)),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,...debug},(key,value)=>key==='samplePositions'||key==='windows'||key==='agents'?undefined:value,2);
 if(soakRunning&&elapsed>=nextSample){samples.push({elapsed,debug,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures});nextSample=elapsed+1;drawChart();}
 if(recorder?.state==='recording'){
  ctx.drawImage(renderer.domElement,0,0,composite.width,composite.height);ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(0,0,composite.width,108);ctx.fillStyle='#fff';ctx.font='13px monospace';ctx.fillText(`Kuroshio runtime | elapsed ${elapsed.toFixed(1)} s | ${renderer.info.render.calls} draws | ${renderer.info.render.triangles} triangles`,12,22);
  const animals=debug.animals??[];animals.forEach((a:any,i:number)=>ctx.fillText(`${a.id}: ${a.state}  ${a.speed?.toFixed(2)}m/s ${a.frequency?.toFixed(2)}Hz R=${a.radius?.toFixed(1)}m bank=${a.bank?.toFixed(1)}°`,12,43+i*18));
 }
}
function drawChart(){const c=$<HTMLCanvasElement>('chart'),x=c.getContext('2d')!;x.fillStyle='#192126';x.fillRect(0,0,c.width,c.height);const panels=[{label:'Frequency Hz (0–0.6)',field:'frequency',min:0,max:.6},{label:'Bank degrees (−50–50)',field:'bank',min:-50,max:50},{label:'Turn radius m (0–100; clipped)',field:'radius',min:0,max:100}];panels.forEach((p,row)=>{const top=row*80;x.strokeStyle='#637178';x.strokeRect(35,top+16,c.width-40,58);x.fillStyle='#c0c9cc';x.font='11px monospace';x.fillText(p.label+' / 0–600 s',40,top+12);for(let k=0;k<4;k++){x.strokeStyle=['#d2be87','#96c4bb','#b09fcb','#91b4d5'][k];x.beginPath();let started=false;for(const s of samples){const a=s.debug.animals?.[k];if(!a)continue;const value=Math.max(p.min,Math.min(p.max,a[p.field]??p.max)),px=35+s.elapsed/600*(c.width-40),py=top+74-(value-p.min)/(p.max-p.min)*58;started?x.lineTo(px,py):x.moveTo(px,py);started=true;}x.stroke();}});}

function reset(){elapsed=0;motion=new ArcadeAnimalMotion();schoolReview.root.removeFromParent();schoolReview.dispose();schoolReview=createArcadeSchools({seed:91626,obstacles:arcadeObstacles()});scene.add(schoolReview.root);if(street){street.dispose();streetScene=undefined;street=undefined as never;}last=performance.now();void select();}
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'暫停':'播放';last=performance.now();};$('restart').onclick=reset;$<HTMLSelectElement>('subject').onchange=()=>void select();$<HTMLSelectElement>('view').onchange=()=>draw(0);for(const id of ['gray','neutral','ortho'])$<HTMLInputElement>(id).onchange=()=>draw(0);
$('clip').onclick=()=>{
 const button=$<HTMLButtonElement>('clip');button.disabled=true;playing=true;$('play').textContent='暫停';last=performance.now();const stream=renderer.domElement.captureStream(24),parts:BlobPart[]=[],clip=new MediaRecorder(stream,{mimeType:'video/webm',videoBitsPerSecond:3000000});clip.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};clip.onstop=()=>{stream.getTracks().forEach(track=>track.stop());download(`kuroshio-${$<HTMLSelectElement>('subject').value}-30s.webm`,new Blob(parts,{type:'video/webm'}));button.disabled=false;};clip.start();setTimeout(()=>{if(clip.state==='recording')clip.stop();},30000);
};
$('soak').onclick=async()=>{
 $<HTMLSelectElement>('subject').value='street';reset();await select();while(loading)await new Promise(r=>setTimeout(r,50));samples.length=0;nextSample=0;frameMs=[];soakStart=performance.now();soakRunning=true;playing=true;last=performance.now();recordStopped=false;recordChunks=[];composite.width=960;composite.height=Math.round(960/camera.aspect);captureStream=composite.captureStream(12);
 const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';recorder=new MediaRecorder(captureStream,{mimeType:mime,videoBitsPerSecond:1800000});recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data);};recorder.onstop=()=>{download('kuroshio-debug-5min.webm',new Blob(recordChunks,{type:mime}));captureStream?.getTracks().forEach(t=>t.stop());};recorder.start(1000);$('status').textContent='10 分鐘驗收中；前 5 分鐘錄影';
};
function tick(now:number){const rawDt=(now-last)/1000,dt=Math.min(.1,rawDt);last=now;if(playing){elapsed+=dt;draw(dt);}if(soakRunning){frameMs.push(rawDt*1000);if(elapsed>=300&&!recordStopped){recorder?.stop();recordStopped=true;}if(elapsed>=600){soakRunning=false;playing=false;const sorted=frameMs.slice().sort((a,b)=>a-b);download('kuroshio-10min-runtime.json',new Blob([JSON.stringify({wallSeconds:(now-soakStart)/1000,simSeconds:elapsed,frameMs:{median:sorted[Math.floor(sorted.length*.5)],p95:sorted[Math.floor(sorted.length*.95)]},samples},null,2)],{type:'application/json'}));$<HTMLCanvasElement>('chart').toBlob(blob=>{if(blob)download('kuroshio-frequency-chart.png',blob);});$('status').textContent='10 分鐘播放完成，下載驗收資料';}}raf=requestAnimationFrame(tick);}
void select();raf=requestAnimationFrame(tick);addEventListener('pagehide',()=>{cancelAnimationFrame(raf);if(recorder?.state==='recording')recorder.stop();models.forEach(m=>m.dispose());smallModels.forEach(m=>m.dispose());schoolReview.dispose();street?.dispose();gray.dispose();renderer.dispose();},{once:true});
