import * as THREE from 'three';
import './snowwindow-camera.css';
import {prepareSnowwindow} from '../places/snowwindow/index.ts';
import {createSceneClock} from '../player/SceneClock.ts';
import {sampleTime,formatHour} from '../systems/TimeOfDay.ts';

type VectorKey='position'|'target';type Axis='x'|'y'|'z';
type Draft={version:1;position:number[];target:number[];fov:number;hour:number};
const draftKey='quiet-places:snowwindow-camera:draft:v1';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const stage=$<HTMLDivElement>('stage'),status=$<HTMLParagraphElement>('status');
const renderer=new THREE.WebGLRenderer({antialias:true});
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','雪落海窗的相機預覽');stage.replaceChildren(renderer.domElement);
const camera=new THREE.PerspectiveCamera(56,1,.1,700),scene=new THREE.Scene(),clock=createSceneClock();
let place:ReturnType<Awaited<ReturnType<typeof prepareSnowwindow>>>|undefined;
let baseline:Draft|undefined,raf=0,last=performance.now(),disposed=false;
const values:{position:THREE.Vector3;target:THREE.Vector3}={position:new THREE.Vector3(),target:new THREE.Vector3()};
const inputs=new Map<string,{range:HTMLInputElement;number:HTMLInputElement;output:HTMLOutputElement}>();
const setStatus=(message:string)=>{status.textContent=message;};
function finite(value:number,label:string){if(!Number.isFinite(value))throw new Error(`${label} 必須是有限數值。`);return value;}
function candidate():Draft{return {version:1,position:values.position.toArray(),target:values.target.toArray(),fov:finite(camera.fov,'FOV'),hour:finite(Number($<HTMLInputElement>('hour').value),'時刻')};}
function validate(next:Draft){if(next.position.length!==3||next.target.length!==3)throw new Error('鏡頭座標必須各有三個值。');next.position.forEach((n,i)=>finite(n,`位置 ${'XYZ'[i]}`));next.target.forEach((n,i)=>finite(n,`注視點 ${'XYZ'[i]}`));if(!Number.isFinite(next.fov)||next.fov<20||next.fov>100)throw new Error('FOV 必須介於 20 到 100 度。');if(!Number.isFinite(next.hour)||next.hour<0||next.hour>24)throw new Error('時刻必須介於 00:00 到 24:00。');if(new THREE.Vector3().fromArray(next.position).distanceToSquared(new THREE.Vector3().fromArray(next.target))<1e-8)throw new Error('相機位置與注視點不能重合。');}
function apply(next:Draft,announce=true){validate(next);values.position.fromArray(next.position);values.target.fromArray(next.target);camera.position.copy(values.position);camera.lookAt(values.target);camera.fov=next.fov;camera.updateProjectionMatrix();$<HTMLInputElement>('hour').value=String(next.hour);syncInputs();if(announce)setStatus('候選已更新；正式場景設定未寫入。');draw(0);}
function syncInputs(){for(const [key,entry] of inputs){const [group,axis]=key.split(':') as [VectorKey,Axis];const value=values[group][axis];entry.range.value=String(value);entry.number.value=String(value);entry.output.value=value.toFixed(2);} $<HTMLInputElement>('fov-range').value=String(camera.fov);$<HTMLInputElement>('fov-number').value=String(camera.fov);$<HTMLOutputElement>('fov-value').value=`${camera.fov.toFixed(1)}°`;const hour=Number($<HTMLInputElement>('hour').value);$<HTMLOutputElement>('hour-value').value=formatHour(hour);}
function changeVector(group:VectorKey,axis:Axis,raw:string){const value=raw.trim()===""?NaN:Number(raw);try{finite(value,`${group} ${axis}`);const next=candidate();next[group]['xyz'.indexOf(axis)]=value;apply(next);}catch(error){setStatus(String(error));syncInputs();}}
function setupInputs(){document.querySelectorAll<HTMLInputElement>('input[data-group][data-axis][type=range]').forEach(range=>{const group=range.dataset.group as VectorKey,axis=range.dataset.axis as Axis;const number=range.parentElement!.querySelector<HTMLInputElement>('.numeric')!,output=range.parentElement!.querySelector<HTMLOutputElement>('output')!;const key=`${group}:${axis}`;const label=`${group==='position'?'位置':'注視點'} ${axis.toUpperCase()}`;range.setAttribute('aria-label',label);number.setAttribute('aria-label',`${label} 數值`);inputs.set(key,{range,number,output});range.addEventListener('input',()=>changeVector(group,axis,range.value));number.addEventListener('input',()=>{if(number.value.trim()!==''&&Number.isFinite(number.valueAsNumber))changeVector(group,axis,number.value);});number.addEventListener('change',()=>changeVector(group,axis,number.value));});const fovRange=$<HTMLInputElement>('fov-range'),fovNumber=$<HTMLInputElement>('fov-number');fovRange.setAttribute('aria-label','視角');fovNumber.setAttribute('aria-label','視角數值');const changeFov=(raw:string)=>{try{const next=candidate();next.fov=Number(raw);apply(next);}catch(error){setStatus(String(error));syncInputs();}};fovRange.addEventListener('input',()=>changeFov(fovRange.value));fovNumber.addEventListener('input',()=>{if(fovNumber.valueAsNumber>=20&&fovNumber.valueAsNumber<=100)changeFov(fovNumber.value);});fovNumber.addEventListener('change',()=>changeFov(fovNumber.value));$<HTMLInputElement>('hour').addEventListener('input',()=>{syncInputs();draw(0);});}
function draw(dt:number){if(!place)return;const hour=Number($<HTMLInputElement>('hour').value);place.update(dt,clock.elapsed,{...sampleTime(hour),beamStrength:1,lowQuality:false});renderer.render(scene,camera);const size=renderer.getSize(new THREE.Vector2());$<HTMLElement>('viewport-readout').textContent=`${Math.round(size.x)} × ${Math.round(size.y)}`;}
function resize(){const rect=stage.getBoundingClientRect();if(rect.width<1||rect.height<1)return;renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();draw(0);}
function json(){const root=scene.getObjectByName('snowwindow-room');const size=renderer.getSize(new THREE.Vector2());return JSON.stringify({tool:'snowwindow-camera-preview',previewOnly:true,camera:candidate(),viewport:{width:Math.round(size.x),height:Math.round(size.y)},responsiveRootOffset:root?.position.toArray()??null},null,2);}
async function copy(){const text=json();try{await navigator.clipboard.writeText(text);$<HTMLTextAreaElement>('json-fallback').style.display='none';setStatus('鏡頭參數已複製。');}catch{$<HTMLTextAreaElement>('json-fallback').value=text;$<HTMLTextAreaElement>('json-fallback').style.display='block';$<HTMLTextAreaElement>('json-fallback').select();setStatus('剪貼簿不可用，JSON 已選取，可直接複製。');}}
function pause(){clock.setPaused(!clock.paused);$<HTMLButtonElement>('pause').textContent=clock.paused?'繼續流動':'暫停流動';$<HTMLButtonElement>('pause').setAttribute('aria-pressed',String(clock.paused));$<HTMLElement>('flow-readout').textContent=clock.paused?'已暫停':'流動中';}
function saveDraft(){try{localStorage.setItem(draftKey,JSON.stringify(candidate()));setStatus('本機草稿已儲存；未改動正式設定。');}catch{setStatus('無法寫入本機草稿。');}}
function restoreDraft(){try{const raw=localStorage.getItem(draftKey);if(!raw)throw new Error('尚無本機草稿。');apply(JSON.parse(raw) as Draft);setStatus('已還原本機草稿；尚未採用到正式設定。');}catch(error){setStatus(String(error));}}
function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);resizeObserver.disconnect();clock.dispose();place?.dispose();renderer.dispose();}
function tick(now:number){const dt=(now-last)/1000;last=now;if(!document.hidden&&!clock.paused){clock.advance(dt);draw(dt);}raf=requestAnimationFrame(tick);}
setupInputs();
$<HTMLButtonElement>('pause').onclick=pause;$<HTMLButtonElement>('reset').onclick=()=>{if(baseline)apply(structuredClone(baseline));};$<HTMLButtonElement>('copy').onclick=()=>void copy();$<HTMLButtonElement>('save-draft').onclick=saveDraft;$<HTMLButtonElement>('restore-draft').onclick=restoreDraft;
$<HTMLButtonElement>('panel-toggle').onclick=()=>{document.body.classList.toggle('panel-hidden');const hidden=document.body.classList.contains('panel-hidden'),button=$<HTMLButtonElement>('panel-toggle');button.textContent=hidden?'顯示控制':'收起控制';button.setAttribute('aria-expanded',String(!hidden));requestAnimationFrame(resize);};
const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);document.addEventListener('visibilitychange',()=>{if(document.hidden&&!clock.paused)pause();});window.addEventListener('pagehide',dispose,{once:true});
try{const factory=await prepareSnowwindow();place=factory(scene,renderer);renderer.toneMapping=place.toneMapping??THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=place.exposure??1;const initial:Draft={version:1,position:[...place.position],target:[...place.target],fov:place.fov??56,hour:12};baseline=structuredClone(initial);apply(initial,false);resize();raf=requestAnimationFrame(tick);setStatus('雪景已就緒，拖曳滑桿即可調整鏡頭。');}catch(error){setStatus(`載入失敗：${String(error)}`);dispose();}
