import * as THREE from 'three';

export interface MedakaMetadata {
  duration: number; fps: number; frameCount: number; fishCount: number; stride: number;
  states: string[];
  fish: Array<{length: number; colorVariant: number; motionPhase: number; motionSeed: number}>;
  events: Array<{time: number; initiator: number; members: number[]; target: number[]; reactionWindow: number[]}>;
}
export interface MedakaMotionSample {
  position: THREE.Vector3; quaternion: THREE.Quaternion;
  speed: number; phase: number; q: number; acceleration: number; state: number;
  length: number; colorVariant: number;
}
export interface PreparedMedakaMotion {
  metadata: MedakaMetadata;
  /** Samples the closed 120-second cache; elapsed wraps safely for negative/non-finite clocks. */
  sample(elapsed: number, index: number): MedakaMotionSample;
}

const STRIDE = 12;
const modulo = (value: number, divisor: number) => ((value % divisor) + divisor) % divisor;

/** Decodes the little-endian, frame-major Float32 asset generated by Blender tooling. */
export function decodeMedakaMotion(metadata: MedakaMetadata, bytes: ArrayBuffer): PreparedMedakaMotion {
  if (metadata.stride !== STRIDE || metadata.frameCount < 2 || metadata.fishCount < 1 || metadata.fps <= 0)
    throw new Error('Invalid medaka motion metadata.');
  const values = new Float32Array(bytes);
  if (values.length !== metadata.frameCount * metadata.fishCount * metadata.stride)
    throw new Error('Medaka motion binary length does not match metadata.');
  return {
    metadata,
    sample(elapsed: number, index: number): MedakaMotionSample {
      if (!Number.isInteger(index) || index < 0 || index >= metadata.fishCount) throw new RangeError('Medaka fish index is out of range.');
      const time = Number.isFinite(elapsed) ? modulo(elapsed, metadata.duration) : 0;
      const exact = time * metadata.fps;
      const lowFrame = Math.min(metadata.frameCount - 2, Math.floor(exact));
      const mix = exact - lowFrame;
      const a = (lowFrame * metadata.fishCount + index) * STRIDE;
      const b = a + metadata.fishCount * STRIDE;
      const position = new THREE.Vector3(); const quaternion = new THREE.Quaternion();
      const result: MedakaMotionSample = {position, quaternion, speed: 0, phase: 0, q: 0, acceleration: 0, state: 0, length: 0, colorVariant: 0};
      position.set(values[a], values[a + 1], values[a + 2]).lerp(new THREE.Vector3(values[b], values[b + 1], values[b + 2]), mix);
      // Use the same bounded, low-speed-stable heading baked into Blender.
      quaternion.set(values[a+3],values[a+4],values[a+5],values[a+6]).normalize()
        .slerp(new THREE.Quaternion(values[b+3],values[b+4],values[b+5],values[b+6]).normalize(),mix);
      result.speed = THREE.MathUtils.lerp(values[a + 7], values[b + 7], mix);
      // Phase is circular, so no animation pop when the stored phase wraps 2π.
      result.phase = modulo(THREE.MathUtils.lerp(values[a + 8], values[b + 8], mix), Math.PI * 2);
      result.q = THREE.MathUtils.lerp(values[a + 9], values[b + 9], mix);
      result.state = mix < .5 ? Math.round(values[a + 10]) : Math.round(values[b + 10]);
      result.acceleration = THREE.MathUtils.lerp(values[a + 11], values[b + 11], mix);
      result.length = metadata.fish[index].length; result.colorVariant = metadata.fish[index].colorVariant;
      return result;
    },
  };
}

/** Fetches both public cache files. The caller owns no WebGL resources. */
export async function prepareMedakaMotion(): Promise<PreparedMedakaMotion> {
  const [metaResponse, binaryResponse] = await Promise.all([fetch('/models/medaka-motion.json'), fetch('/models/medaka-motion.bin')]);
  if (!metaResponse.ok || !binaryResponse.ok) throw new Error('Medaka motion cache could not be loaded.');
  return decodeMedakaMotion(await metaResponse.json() as MedakaMetadata, await binaryResponse.arrayBuffer());
}
