import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const result=document.querySelector('#result')!,canvas=document.querySelector('canvas')!,select=document.querySelector('select') as HTMLSelectElement,toggle=document.querySelector('button')!;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(1440,560,false);renderer.setScissorTest(true);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x10171a);scene.add(new THREE.HemisphereLight(0xdce9ec,0x18242a,2.1));const key=new THREE.DirectionalLight(0xfff4dc,2.8);key.position.set(2,4,3);scene.add(key);const rim=new THREE.DirectionalLight(0x91c5d7,1.7);rim.position.set(-3,2,-2);scene.add(rim);
const views=[[new THREE.Vector3(1,0,0),'side'],[new THREE.Vector3(0,1,0),'top'],[new THREE.Vector3(1,.7,1),'three-quarter']] as const;let camera:THREE.OrthographicCamera;const target=new THREE.Vector3(),names=['IDLE_HOVER','SLOW_CRUISE','GLIDE','TURN_LEFT','TURN_RIGHT','SLIGHT_RISE','SLIGHT_DESCEND','PAUSE'];
let mixer:THREE.AnimationMixer,clips=new Map<string,THREE.AnimationClip>(),paused=false,school=false,time=0,last=performance.now(),active='';
function selectClip(name:string){if(!mixer)return;const clip=clips.get(name);if(!clip)throw Error(`missing ${name}`);mixer.stopAllAction();mixer.clipAction(clip).play();active=name;select.value=name;mixer.setTime(time%clip.duration);}
function layout(root:THREE.Object3D,all:THREE.Object3D[]){all.forEach((item,index)=>{item.visible=school||item===root;item.position.set(school?(index%3-1)*.55:0,school?(Math.floor(index/3)-1)*.28:0,school?Math.sin(index*2.3)*.28:0);});}
function render(){if(!camera)return;for(let i=0;i<views.length;i++){camera.position.copy(target).addScaledVector(views[i][0].normalize(),3);camera.lookAt(target);renderer.setViewport(i*480,0,480,560);renderer.setScissor(i*480,0,480,560);renderer.render(scene,camera);}result.textContent=`GLB · KOI_04 · ${active} · t=${time.toFixed(2)}s · ${paused?'paused':'playing'} · ${school?'7 fish layout':'single fish'}`;}
function frame(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused){time+=dt;mixer?.setTime(time%(clips.get(active)?.duration??1));}render();requestAnimationFrame(frame);}
try{const gltf=await new GLTFLoader().loadAsync('/models/long-fin-koi-school.glb'),root=gltf.scene.getObjectByName('KOI_04');if(!root)throw Error('KOI_04 missing');const roots=Array.from({length:7},(_,i)=>gltf.scene.getObjectByName(`KOI_${String(i+1).padStart(2,'0')}`)).filter((item):item is THREE.Object3D=>Boolean(item));if(roots.length!==7)throw Error('seven KOI roots missing');roots.forEach(item=>{item.traverse(node=>{if(!(node instanceof THREE.Mesh))return;if(node.name.includes('LFK_RAY'))node.visible=false;if(node.name.includes('LFK_FIN')){const materials=Array.isArray(node.material)?node.material:[node.material];materials.forEach(material=>{material.transparent=true;material.depthWrite=false;if(material instanceof THREE.MeshPhysicalMaterial)material.transmission=0;material.needsUpdate=true;});}});scene.add(item);});layout(root,roots);root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(root),size=bounds.getSize(new THREE.Vector3()),centre=bounds.getCenter(new THREE.Vector3());target.copy(centre);target.z+=.04;const half=Math.max(size.x,size.y,size.z)*.72,aspect=480/560;camera=new THREE.OrthographicCamera(-half*aspect,half*aspect,half,-half,.01,10);mixer=new THREE.AnimationMixer(scene);for(const name of names){const clip=gltf.animations.find(item=>item.name===`KOI_ACT_${name}`);if(!clip)throw Error(`KOI_ACT_${name} missing`);clips.set(name,clip);}select.innerHTML=names.map(name=>`<option value="${name}">${name}</option>`).join('');select.addEventListener('change',()=>selectClip(select.value));toggle.addEventListener('click',()=>{school=!school;toggle.textContent=school?'單尾 KOI_04':'七尾編排';layout(root,roots);const h=school?1.12:half;camera.left=-h*aspect;camera.right=h*aspect;camera.top=h;camera.bottom=-h;camera.updateProjectionMatrix();});selectClip('SLOW_CRUISE');(window as Window&{longFinReview:unknown}).longFinReview={setTime(seconds:number){time=Math.max(0,seconds);mixer.setTime(time%(clips.get(active)?.duration??1));render();},advance(seconds:number){time=Math.max(0,time+seconds);mixer.setTime(time%(clips.get(active)?.duration??1));render();},pause(value=!paused){paused=value;render();},inspect(){return {asset:'long-fin-koi-school.glb',active,time,paused,school,views:views.map(item=>item[1]),tailQuaternion:root.getObjectByName('tail_tip_3')?.quaternion.toArray(),textures:renderer.info.memory.textures,programs:renderer.info.programs?.length};}};requestAnimationFrame(frame);}catch(error){result.textContent=`FAIL ${String(error)}`;console.error(error);}
