import * as THREE from 'three';
import {prepareMedaka} from '../src/places/afterlight/Medaka.ts';
import {prepareMedakaMotion} from '../src/places/afterlight/MedakaMotion.ts';

const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1440,480);renderer.setPixelRatio(1);renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.4;document.querySelector('#stage')!.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#18201f');scene.add(new THREE.HemisphereLight('#cad9d1','#0e1716',1.4));const key=new THREE.DirectionalLight('#fff1d2',2.2);key.position.set(.8,3,-1);scene.add(key);
const parent=new THREE.Group();scene.add(parent);const factory=await prepareMedaka(),shoal=factory(parent),motion=await prepareMedakaMotion();
const cameras=[new THREE.PerspectiveCamera(32,1,.01,10),new THREE.PerspectiveCamera(32,1,.01,10),new THREE.PerspectiveCamera(38,1,.01,10)];
const debug=new THREE.Group();scene.add(debug);const marker=new THREE.Mesh(new THREE.SphereGeometry(.012,8,6),new THREE.MeshBasicMaterial({color:'#ffcf69'}));debug.add(marker);const line=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:'#7dc9e8'}));debug.add(line);
let time=12,playing=false,start=0;const result=document.querySelector('#result')!,seek=document.querySelector<HTMLInputElement>('#seek')!;
const targetMarker=new THREE.Mesh(new THREE.SphereGeometry(.018,8,6),new THREE.MeshBasicMaterial({color:'#ee915c',wireframe:true}));debug.add(targetMarker);
for(const [x,y,z,rx,ry,rz] of [[1.57,.67,-.38,.16,.80,.13],[1.28,.92,-.13,.18,.23,.17],[1.28,.92,-.63,.18,.23,.17]]){
 const obstacle=new THREE.Mesh(new THREE.SphereGeometry(1,12,8),new THREE.MeshBasicMaterial({color:'#658f71',wireframe:true,transparent:true,opacity:.35}));
 obstacle.position.set(x,y,z);obstacle.scale.set(rx,ry,rz);debug.add(obstacle);
}
function draw(){shoal.update(time,1);const poses=Array.from({length:motion.metadata.fishCount},(_,index)=>{const pose=motion.sample(time,index);return {position:pose.position.clone(),quaternion:pose.quaternion.clone(),state:pose.state};});const centroid=poses.reduce((sum,pose)=>sum.add(pose.position),new THREE.Vector3()).multiplyScalar(1/poses.length),hero=poses[0].position;marker.position.copy(centroid);const event=motion.metadata.events.filter(event=>event.time<=time).at(-1);targetMarker.visible=Boolean(event);if(event)targetMarker.position.set(...event.target as [number,number,number]);line.geometry.setFromPoints(poses.map(pose=>pose.position));debug.visible=(document.querySelector('#debug') as HTMLInputElement).checked;cameras[0].position.copy(hero).add(new THREE.Vector3(0,.035,.075));cameras[0].lookAt(hero);cameras[1].position.copy(hero).add(new THREE.Vector3(.075,.018,0));cameras[1].lookAt(hero);cameras[2].position.copy(centroid).add(new THREE.Vector3(.75,.6,.9));cameras[2].lookAt(centroid);renderer.setScissorTest(true);cameras.forEach((camera,index)=>{renderer.setViewport(index*480,0,480,480);renderer.setScissor(index*480,0,480,480);renderer.render(scene,camera);});renderer.setScissorTest(false);seek.value=String(time);result.textContent=JSON.stringify({time,state:motion.metadata.states[poses[0].state],centroid:centroid.toArray().map(n=>n.toFixed(3)),fishCount:poses.length,events:motion.metadata.events.filter(event=>Math.abs(event.time-time)<1.2)},null,2);}
document.querySelector('#play')!.addEventListener('click',()=>{playing=!playing;start=performance.now()-time*1000;document.querySelector('#play')!.textContent=playing?'暫停':'播放 120 秒';});document.querySelector('#fixed')!.addEventListener('click',()=>{playing=false;time=time===12?47:83;draw();});document.querySelector('#states')!.addEventListener('click',()=>{playing=false;time=(time+7.5)%120;draw();});seek.addEventListener('input',()=>{playing=false;time=Number(seek.value);draw();});document.querySelector('#debug')!.addEventListener('change',draw);function tick(now:number){if(playing)time=(now-start)/1000%120;draw();requestAnimationFrame(tick);}draw();requestAnimationFrame(tick);
