import * as THREE from 'three';
import {seededRandom} from '../../shared/math/seededRandom.ts';
import {createChromisVisuals,setChromisMatrix,commitChromisMatrices,setChromisMotion,type ChromisVisuals} from '../../creatures/chromis/index.ts';
import {createFusilierVisuals,setFusilierMatrix,commitFusilierMatrices,setFusilierMotion,type FusilierVisuals} from '../../creatures/fusilier/index.ts';

export type ArcadeObstacle={min:[number,number,number];max:[number,number,number]};
export type SchoolThreat={position:THREE.Vector3;velocity:THREE.Vector3;radius:number};
export interface ArcadeSchools {root:THREE.Group;update(dt:number,elapsed:number):void;disturb():void;setRareEventsEnabled(enabled:boolean):void;getDebug():unknown;dispose():void;}
type Kind='chromis'|'fusilier'; type Fish={p:THREE.Vector3;previous:THREE.Vector3;v:THREE.Vector3;heading:THREE.Vector3;length:number;phase:number;previousPhase:number;speedBL:number;previousSpeedBL:number;wander:number;home:THREE.Vector3;orientation:THREE.Quaternion;previousOrientation:THREE.Quaternion;alarm:number;refuge:THREE.Vector3;};
type WindowMetric={at:number;chromis:{polarization:number;medianNearestBL:number;state:string};fusilier:{polarization:number;medianNearestBL:number;state:string};penetrations:number};
type School={kind:Kind;fish:Fish[];visual:ChromisVisuals|FusilierVisuals;goal:THREE.Vector3;goalVelocity:THREE.Vector3;events:number;collisionCount:number;nearest:number;medianNearest:number;polarization:number;state:'NORMAL'|'CONTRACT';contractUntil:number;};
const STEP=1/12,UP=new THREE.Vector3(0,1,0),FORWARD=new THREE.Vector3(0,0,-1),tmpMatrix=new THREE.Matrix4(),tmpQuaternion=new THREE.Quaternion(),tmpScale=new THREE.Vector3();
const bounds={min:new THREE.Vector3(.08,.18,-27.8),max:new THREE.Vector3(8.75,2.7,.7)};
const exponentialWait=(random:()=>number,mean:number)=>-Math.log(Math.max(1e-9,1-random()))*mean;

export function createArcadeSchools(options:{seed:number;obstacles:Array<ArcadeObstacle>;sampleThreats?:(time:number)=>ReadonlyArray<SchoolThreat>}):ArcadeSchools {
 const seed=Number.isFinite(options.seed)?options.seed>>>0:1,random=seededRandom(seed),root=new THREE.Group();root.name='KUROSHIO_SMALL_SCHOOLS';
 const chromis=makeSchool('chromis',100,random),fusilier=makeSchool('fusilier',50,random);root.add(chromis.visual.root,fusilier.visual.root);
 let accumulator=0,lastElapsed:number|undefined,simTime=0,rare=true,disposed=false,nextChromisEvent=exponentialWait(random,330),nextFusilierEvent=exponentialWait(random,180),nextWindow=10;const windows:WindowMetric[]=[];
 function advance(){simTime+=STEP;if(rare&&simTime>=nextChromisEvent){chromis.state='CONTRACT';chromis.contractUntil=simTime+1.4+random()*1.6;chromis.events++;nextChromisEvent=chromis.contractUntil+120+exponentialWait(random,210);}if(rare&&simTime>=nextFusilierEvent){fusilier.state='CONTRACT';fusilier.contractUntil=simTime+2+random()*2;fusilier.events++;nextFusilierEvent=fusilier.contractUntil+75+exponentialWait(random,105);}updateGoal(chromis,simTime,random);updateGoal(fusilier,simTime,random);const threats=options.sampleThreats?.(simTime)??[];stepSchool(chromis,options.obstacles,simTime,threats);stepSchool(fusilier,options.obstacles,simTime,threats);if(simTime+1e-9>=nextWindow){windows.push({at:nextWindow,chromis:{polarization:chromis.polarization,medianNearestBL:chromis.medianNearest,state:chromis.state},fusilier:{polarization:fusilier.polarization,medianNearestBL:fusilier.medianNearest,state:fusilier.state},penetrations:chromis.collisionCount+fusilier.collisionCount});nextWindow+=10;}}
 return {root,update(_dt,elapsed){if(disposed)return;const safe=Math.max(0,Number.isFinite(elapsed)?elapsed:0);if(lastElapsed===undefined){lastElapsed=safe;render(chromis,safe,0);render(fusilier,safe,0);return;}const delta=safe-lastElapsed;if(delta<=0){render(chromis,safe,accumulator/STEP);render(fusilier,safe,accumulator/STEP);lastElapsed=safe;return;}lastElapsed=safe;accumulator+=delta;while(accumulator+1e-9>=STEP){advance();accumulator-=STEP;}render(chromis,safe,accumulator/STEP);render(fusilier,safe,accumulator/STEP);},disturb(){if(!rare||disposed)return;chromis.state='CONTRACT';chromis.contractUntil=simTime+2.2;chromis.events++;},setRareEventsEnabled(enabled){rare=enabled;},getDebug(){return {time:simTime,stepHz:12,interpolation:accumulator/STEP,chromis:debug(chromis),fusilier:debug(fusilier),windows,obstacles:options.obstacles.length,rareEventsEnabled:rare};},dispose(){if(disposed)return;disposed=true;chromis.visual.dispose();fusilier.visual.dispose();root.clear();}};
}
function makeSchool(kind:Kind,count:number,r:()=>number):School {const fish:Fish[]=[],phases=new Float32Array(count),lengths=new Float32Array(count),center=kind==='chromis'?new THREE.Vector3(1.43,2.22,-4.12):new THREE.Vector3(1.59,1.7,-8.60);for(let i=0;i<count;i++){const length=(kind==='chromis'?.035:.18)+(kind==='chromis'?.02:.10)*r(),shelter=[new THREE.Vector3(.95,2.16,-4.05),new THREE.Vector3(.68,.42,-2.5),new THREE.Vector3(2.35,.58,-17.6)][i%3],spread=kind==='chromis'?new THREE.Vector3(.62,.34,.85):new THREE.Vector3(.8,.45,1.5),p=(kind==='chromis'?shelter:center).clone().add(new THREE.Vector3((r()-.5)*spread.x,(r()-.5)*spread.y,(r()-.5)*spread.z));const h=new THREE.Vector3(kind==='chromis'?r()-.5:0,(r()-.5)*.12,-1).normalize();phases[i]=r();lengths[i]=length;fish.push({p,previous:p.clone(),v:h.clone().multiplyScalar(length*(kind==='chromis'?.85:1.25)),heading:h,length,phase:phases[i],previousPhase:phases[i],speedBL:kind==='chromis'?.85:1.25,previousSpeedBL:kind==='chromis'?.85:1.25,wander:i*2.399963+phases[i],home:shelter.clone().add(new THREE.Vector3((r()-.5)*.35,(r()-.5)*.20,(r()-.5)*.55)),orientation:new THREE.Quaternion().setFromUnitVectors(FORWARD,h),previousOrientation:new THREE.Quaternion().setFromUnitVectors(FORWARD,h),alarm:0,refuge:p.clone()});}const visual=kind==='chromis'?createChromisVisuals(count,phases,lengths):createFusilierVisuals(count,phases,lengths);return {kind,fish,visual,goal:kind==='chromis'?new THREE.Vector3():center.clone(),goalVelocity:new THREE.Vector3(0,0,-1),events:0,collisionCount:0,nearest:0,medianNearest:0,polarization:0,state:'NORMAL',contractUntil:0};}
function updateGoal(s:School,t:number,_r:()=>number){
 if(s.kind==='chromis'){s.goal.set(.12*Math.sin(t*.07),.08*Math.sin(t*.053),.24*Math.cos(t*.061));}
 else{const phase=-1.1+t*.045,excursion=Math.pow(.5-.5*Math.cos(t*.022),3),excursionRate=3*Math.pow(.5-.5*Math.cos(t*.022),2)*.011*Math.sin(t*.022);s.goal.set(2.75+1.3*Math.sin(phase)+1.1*excursion,1.7+.14*Math.sin(t*.017),-9.6+2.2*Math.cos(phase)-3*excursion);s.goalVelocity.set(1.3*.045*Math.cos(phase)+1.1*excursionRate,.14*.017*Math.cos(t*.017),-2.2*.045*Math.sin(phase)-3*excursionRate).normalize();}
 if(s.state==='CONTRACT'&&t>s.contractUntil)s.state='NORMAL';
}

function stepSchool(s:School,obstacles:ArcadeObstacle[],t:number,threats:ReadonlyArray<SchoolThreat>){const f=s.fish,n=f.length,kind=s.kind,rep=kind==='chromis'?1.5:1.3,align=kind==='chromis'?3:4.2,attract=kind==='chromis'?6:8,base=kind==='chromis'?.85:1.25,px=f.map(a=>a.p.x),py=f.map(a=>a.p.y),pz=f.map(a=>a.p.z),hx=f.map(a=>a.heading.x),hy=f.map(a=>a.heading.y),hz=f.map(a=>a.heading.z),individualNearest=new Array<number>(n).fill(Infinity);let polX=0,polY=0,polZ=0,nearest=Infinity;
 for(let i=0;i<n;i++){const a=f[i];a.previous.copy(a.p);a.previousPhase=a.phase;a.previousSpeedBL=a.speedBL;a.previousOrientation.copy(a.orientation);let threatLevel=0;
  for(const threat of threats){
   if(threat.position.y>6)continue;
   const travel=threat.velocity.clone().multiplyScalar(8),relative=a.p.clone().sub(threat.position),fraction=THREE.MathUtils.clamp(relative.dot(travel)/Math.max(1e-8,travel.lengthSq()),0,1);
   const distance=relative.addScaledVector(travel,-fraction).length()-threat.radius;
   threatLevel=Math.max(threatLevel,1-THREE.MathUtils.smoothstep(distance,1,6));
  }
  if(threatLevel>.2&&a.alarm<.05){
   const gap=THREE.MathUtils.clamp(4.8-3.2*Math.round((4.8-a.p.z)/3.2),-24,-1.6);
   a.refuge.set(kind==='chromis'?Math.max(.55,a.home.x-.3):1.2+.3*Math.sin(a.wander),kind==='chromis'?a.home.y:1.4+.16*Math.sin(a.wander*1.3),kind==='chromis'?a.home.z:gap+.5*Math.sin(a.wander*.8));
  }
  a.alarm=THREE.MathUtils.lerp(a.alarm,threatLevel,1-Math.exp(-STEP/(threatLevel>a.alarm?1.2:12)));
  let rx=0,ry=0,rz=0,ax=0,ay=0,az=0,cx=0,cy=0,cz=0,ac=0,cc=0;for(let j=0;j<n;j++){if(i===j)continue;const dx=px[i]-px[j],dy=py[i]-py[j],dz=pz[i]-pz[j],d=Math.hypot(dx,dy,dz),bl=d/Math.max(a.length,f[j].length);if(d<nearest)nearest=d;if(bl<individualNearest[i])individualNearest[i]=d/a.length;if(bl<rep){const q=12*((rep-bl)/rep)**2/(d+.00001);rx+=dx*q;ry+=dy*q;rz+=dz*q;}if(bl<align){ax+=hx[j];ay+=hy[j];az+=hz[j];ac++;}if(bl<attract){cx+=px[j];cy+=py[j];cz+=pz[j];cc++;}}
  const repLimit=kind==='chromis'?2.2:2.8,repLength=Math.hypot(rx,ry,rz);if(repLength>repLimit){rx*=repLimit/repLength;ry*=repLimit/repLength;rz*=repLimit/repLength;}let dx=(kind==='chromis'?4.0:4.0)*rx,dy=(kind==='chromis'?4.0:4.0)*ry,dz=(kind==='chromis'?4.0:4.0)*rz;if(ac){const wA=kind==='chromis'?.40:3.4,wC=kind==='chromis'?.55:.70;dx+=wA*(ax/ac-a.heading.x)+(cc?wC*(cx/cc-a.p.x)/Math.max(a.length,1e-4):0);dy+=wA*(ay/ac-a.heading.y)+(cc?wC*(cy/cc-a.p.y)/Math.max(a.length,1e-4):0);dz+=wA*(az/ac-a.heading.z)+(cc?wC*(cz/cc-a.p.z)/Math.max(a.length,1e-4):0);}const goalGain=kind==='chromis'?2.4:1.35;if(kind==='chromis'){dx+=goalGain*(a.home.x+s.goal.x+.22*Math.sin(t*.055+a.wander)-a.p.x);dy+=goalGain*(a.home.y+s.goal.y+.11*Math.sin(t*.041+a.wander*1.7)-a.p.y);dz+=goalGain*(a.home.z+s.goal.z+.3*Math.cos(t*.047+a.wander)-a.p.z);}else{dx+=goalGain*s.goalVelocity.x*.65;dy+=goalGain*s.goalVelocity.y*.65;dz+=goalGain*s.goalVelocity.z*.65;dx+=.9*(s.goal.x-a.p.x);dy+=.9*(s.goal.y-a.p.y);dz+=.9*(s.goal.z-a.p.z);}
  if(s.state==='CONTRACT'){const home=kind==='chromis'?a.home:new THREE.Vector3();dx+=2.2*(home.x+s.goal.x-a.p.x);dy+=2.2*(home.y+s.goal.y-a.p.y);dz+=2.2*(home.z+s.goal.z-a.p.z);}
  // Steering wander has its own slow phase: tail cycles must never drive navigation.
  const noise=kind==='chromis'?.30:.06;dx+=noise*Math.sin(t*.19+a.wander);dy+=noise*.20*Math.cos(t*.13+a.wander*1.3);dz+=noise*.72*Math.sin(t*.17+a.wander*.8);dy*=.32;
  // Approach is anticipated; refuge is inside the arcade, with crossings between posts.
  const retreat=THREE.MathUtils.smoothstep(a.alarm,.08,.7);
  if(retreat>0){dx=THREE.MathUtils.lerp(dx,4.5*(a.refuge.x-a.p.x),retreat);dy=THREE.MathUtils.lerp(dy,1.5*(a.refuge.y-a.p.y),retreat);dz=THREE.MathUtils.lerp(dz,3*(a.refuge.z-a.p.z),retreat);}
  const force=obstacleForce(a,obstacles);dx+=force.x*2.4;dy+=force.y*2.4;dz+=force.z*2.4;if(force.colliding)s.collisionCount++;
  // Soft containment starts before the hard safety boundary.
  for(const axis of ['x','y','z'] as const){const margin=axis==='y'?(kind==='chromis'?.18:.35):.8,low=bounds.min[axis]+margin,high=bounds.max[axis]-margin;const push=a.p[axis]<low?(low-a.p[axis])*4:a.p[axis]>high?(high-a.p[axis])*4:0;if(axis==='x')dx+=push;else if(axis==='y')dy+=push;else dz+=push;}
  const horizontal=Math.hypot(dx,dz),maxPitch=THREE.MathUtils.degToRad(kind==='chromis'?18:14);dy=THREE.MathUtils.clamp(dy,-horizontal*Math.tan(maxPitch),horizontal*Math.tan(maxPitch));
  const desired=a.heading.clone().multiplyScalar(kind==='chromis'?.5:2).addScaledVector(new THREE.Vector3(dx,dy,dz),.3);if(desired.lengthSq()<1e-9)desired.copy(a.heading);else desired.normalize();
  const yaw=Math.atan2(-a.heading.x,-a.heading.z),targetYaw=Math.atan2(-desired.x,-desired.z),yawError=Math.atan2(Math.sin(targetYaw-yaw),Math.cos(targetYaw-yaw)),turnLimit=THREE.MathUtils.degToRad(kind==='chromis'?38:28)*STEP,pitch=Math.asin(a.heading.y),targetPitch=THREE.MathUtils.clamp(Math.asin(desired.y),-maxPitch,maxPitch),pitchLimit=THREE.MathUtils.degToRad(kind==='chromis'?10:7)*STEP;
  const nextYaw=yaw+THREE.MathUtils.clamp(yawError*(1-Math.exp(-STEP/.65)),-turnLimit,turnLimit),nextPitch=pitch+THREE.MathUtils.clamp((targetPitch-pitch)*(1-Math.exp(-STEP/1.1)),-pitchLimit,pitchLimit);
  a.orientation.setFromEuler(new THREE.Euler(nextPitch,nextYaw,0,'YXZ'));a.heading.copy(FORWARD).applyQuaternion(a.orientation);const response=1-Math.exp(-STEP/.85);
  const pace=.92+.08*Math.sin(t*.22+a.wander);const desiredSpeed=a.length*base*pace*(s.state==='CONTRACT'?1.25:1)*(1+.5*retreat);a.v.lerp(a.heading.clone().multiplyScalar(desiredSpeed),response);

  // Reject a predicted swept body intersection before it happens. The fallback
  // preserves the tangential component, so a school streams around a post
  // instead of correcting an already-intersecting fish by teleportation.
  let candidate=a.p.clone().addScaledVector(a.v,STEP);if(!sweptClear(a.p,candidate,a.length*.48,obstacles)){const normal=nearestObstacleNormal(a.p,obstacles);a.v.addScaledVector(normal,-a.v.dot(normal));candidate=a.p.clone().addScaledVector(a.v,STEP);if(!sweptClear(a.p,candidate,a.length*.48,obstacles)){a.v.multiplyScalar(.25);candidate=a.p.clone().addScaledVector(a.v,STEP);}}
  a.p.copy(candidate);contain(a);a.speedBL=a.v.length()/a.length;const frequency=kind==='chromis'?.65+.55*a.speedBL:.70+.95*a.speedBL;a.phase+=frequency*STEP;if(a.v.lengthSq()>1e-10){const speed=a.v.length();polX+=a.v.x/speed;polY+=a.v.y/speed;polZ+=a.v.z/speed;}
 }
 individualNearest.sort((a,b)=>a-b);s.nearest=nearest;s.medianNearest=individualNearest[Math.floor(n*.5)];s.polarization=Math.hypot(polX,polY,polZ)/n;
}
function obstacleForce(a:Fish,obstacles:ArcadeObstacle[]){const out=new THREE.Vector3() as THREE.Vector3&{colliding:boolean};out.colliding=false;for(const box of obstacles){const min=box.min,max=box.max,x=a.p.x,y=a.p.y,z=a.p.z,inside=x>min[0]&&x<max[0]&&y>min[1]&&y<max[1]&&z>min[2]&&z<max[2];const qx=Math.max(min[0],Math.min(max[0],x)),qy=Math.max(min[1],Math.min(max[1],y)),qz=Math.max(min[2],Math.min(max[2],z));let nx=x-qx,ny=y-qy,nz=z-qz,d=Math.hypot(nx,ny,nz);if(inside||d<.0001){const faces=[[x-min[0],-1,0,0],[max[0]-x,1,0,0],[y-min[1],0,-1,0],[max[1]-y,0,1,0],[z-min[2],0,0,-1],[max[2]-z,0,0,1]];faces.sort((a,b)=>a[0]-b[0]);nx=faces[0][1];ny=faces[0][2];nz=faces[0][3];d=0;out.colliding=true;}else{nx/=d;ny/=d;nz/=d;}const safe=a.length*2.5;if(d<safe){const strength=2.8*(1-d/safe)**2;out.x+=nx*strength;out.y+=ny*strength;out.z+=nz*strength;const into=a.v.x*nx+a.v.y*ny+a.v.z*nz;if(into<0){out.x-=nx*into*.8;out.y-=ny*into*.8;out.z-=nz*into*.8;}}}return out;}
function sweptClear(a:THREE.Vector3,b:THREE.Vector3,r:number,obstacles:ArcadeObstacle[]){for(let i=0;i<=3;i++){const p=a.clone().lerp(b,i/3);for(const box of obstacles)if(p.x>box.min[0]-r&&p.x<box.max[0]+r&&p.y>box.min[1]-r&&p.y<box.max[1]+r&&p.z>box.min[2]-r&&p.z<box.max[2]+r)return false;}return true;}
function nearestObstacleNormal(p:THREE.Vector3,obstacles:ArcadeObstacle[]){let best=Infinity,normal=new THREE.Vector3(1,0,0);for(const box of obstacles){const qx=Math.max(box.min[0],Math.min(box.max[0],p.x)),qy=Math.max(box.min[1],Math.min(box.max[1],p.y)),qz=Math.max(box.min[2],Math.min(box.max[2],p.z)),v=new THREE.Vector3(p.x-qx,p.y-qy,p.z-qz),d=v.lengthSq();if(d<best){best=d;normal=d>1e-9?v.normalize():normal;}}return normal;}
function contain(a:Fish){a.p.clamp(bounds.min,bounds.max);}
function render(s:School,elapsed:number,alpha:number){for(let i=0;i<s.fish.length;i++){const f=s.fish[i],p=f.previous.clone().lerp(f.p,alpha),phase=THREE.MathUtils.lerp(f.previousPhase,f.phase,alpha),speed=THREE.MathUtils.lerp(f.previousSpeedBL,f.speedBL,alpha);tmpQuaternion.copy(f.previousOrientation).slerp(f.orientation,alpha);tmpScale.setScalar(f.length);tmpMatrix.compose(p,tmpQuaternion,tmpScale);if(s.kind==='chromis'){setChromisMatrix(s.visual as ChromisVisuals,i,tmpMatrix);setChromisMotion(s.visual as ChromisVisuals,i,phase,speed);}else{setFusilierMatrix(s.visual as FusilierVisuals,i,tmpMatrix);setFusilierMotion(s.visual as FusilierVisuals,i,phase,speed);}}if(s.kind==='chromis'){commitChromisMatrices(s.visual as ChromisVisuals);(s.visual as ChromisVisuals).update(elapsed);}else{commitFusilierMatrices(s.visual as FusilierVisuals);(s.visual as FusilierVisuals).update(elapsed);}}

function debug(s:School){return {count:s.fish.length,state:s.state,events:s.events,polarization:s.polarization,minimumNearestNeighborBL:s.nearest/(s.fish[0]?.length??1),medianNearestNeighborBL:s.medianNearest,meanAlarm:s.fish.reduce((v,f)=>v+f.alarm,0)/s.fish.length,meanSpeedBL:s.fish.reduce((v,f)=>v+f.speedBL,0)/s.fish.length,actualPenetrations:s.collisionCount,goal:s.goal.toArray(),agents:s.fish.map(f=>({position:f.p.toArray(),previous:f.previous.toArray(),heading:f.heading.toArray(),speedBL:f.speedBL,length:f.length,phase:f.phase,alarm:f.alarm,refuge:f.refuge.toArray()}))};}

