import * as THREE from 'three';
import {addBendAttribute,animatedStandard,fishBodyGeometry,setInstanceBend} from '../chromis/index.ts';

export interface FusilierVisuals { root:THREE.Group; update(elapsed:number):void; dispose():void; }
export function createFusilierVisuals(count:number,phases:Float32Array,lengths:Float32Array):FusilierVisuals {
 const root=new THREE.Group();root.name='PTEROCAESIO_DIGRAMMA_INSTANCED';
 const body=new THREE.InstancedMesh(fishBodyGeometry(1,.12,.27,22,14),animatedStandard('#6fa6ad','#6fa6ad'),count);body.name='FUSILIER_SPINDLE_BODY';
 const fins=new THREE.InstancedMesh(fusilierFins(),animatedStandard('#5f8994','#5f8994',true),count);fins.name='FUSILIER_FINS_AND_FORK';
 const eyes=new THREE.InstancedMesh(pairedEyes(),new THREE.MeshStandardMaterial({color:'#142024',roughness:.45}),count);eyes.name='FUSILIER_LATERAL_EYES';
 const stripes=makeStripes(count,phases,lengths);root.add(body,fins,eyes,stripes);
 // These remain non-casters, while their standard materials receive the same
 // directional shadow map as the surrounding arcade geometry.
 for(const mesh of [body,fins,eyes,stripes]){motion(mesh.geometry,phases,lengths,.025);mesh.castShadow=false;mesh.receiveShadow=true;mesh.frustumCulled=false;}
 const initial=new THREE.Matrix4();for(let i=0;i<count;i++){initial.makeScale(lengths[i],lengths[i],lengths[i]);for(const mesh of [body,fins,eyes,stripes])mesh.setMatrixAt(i,initial);}for(const mesh of [body,fins,eyes,stripes])mesh.instanceMatrix.needsUpdate=true;
 return {root,update(){},dispose(){for(const mesh of [body,fins,eyes,stripes]){mesh.geometry.dispose();(mesh.material as THREE.Material).dispose();}root.clear();}};
}
export function setFusilierMatrix(v:FusilierVisuals,i:number,m:THREE.Matrix4){for(const child of v.root.children)if(child instanceof THREE.InstancedMesh)child.setMatrixAt(i,m);}
export function commitFusilierMatrices(v:FusilierVisuals){for(const child of v.root.children)if(child instanceof THREE.InstancedMesh)child.instanceMatrix.needsUpdate=true;}
/** `bend`: shared-locomotion C-bend at the tail, body lengths (+X = fish's right). */
export function setFusilierMotion(v:FusilierVisuals,index:number,phase:number,speedBL:number,bend=0){for(const child of v.root.children)if(child instanceof THREE.InstancedMesh){const p=child.geometry.getAttribute('aPhase') as THREE.InstancedBufferAttribute,a=child.geometry.getAttribute('aTailAmplitude') as THREE.InstancedBufferAttribute;p.setX(index,phase);a.setX(index,Math.min(.065,.014+Math.max(0,speedBL)*.022));p.needsUpdate=true;a.needsUpdate=true;setInstanceBend(child,index,bend);}}
function motion(g:THREE.BufferGeometry,p:Float32Array,l:Float32Array,a:number){g.setAttribute('aPhase',new THREE.InstancedBufferAttribute(p,1));g.setAttribute('aLength',new THREE.InstancedBufferAttribute(l,1));g.setAttribute('aTailAmplitude',new THREE.InstancedBufferAttribute(l.map(()=>a),1));addBendAttribute(g,l.length);if(!g.getAttribute('aFlutter'))g.setAttribute('aFlutter',new THREE.BufferAttribute(new Float32Array(g.getAttribute('position').count),1));}
function fusilierFins(){const p=[-.055,.005,-.17,-.14,-.025,-.01,-.13,-.018,.14,-.055,.004,.07,.055,.005,-.17,.14,-.025,-.01,.13,-.018,.14,.055,.004,.07,0,.10,.03,0,.22,.16,0,.09,.25,0,.08,.08,0,-.09,.06,0,-.16,.18,0,-.07,.25,0,-.07,.08,0,.015,.32,0,.125,.50,0,.05,.43,0,-.125,.50,0,-.015,.32];const g=new THREE.BufferGeometry(),colors=new Float32Array(p.length),blue=new THREE.Color('#5f8994'),black=new THREE.Color('#142024');for(let k=0;k<p.length/3;k++){const c=k===17||k===19?black:blue;colors.set([c.r,c.g,c.b],k*3);}g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.setIndex([0,1,2,0,2,3,4,6,5,4,7,6,8,9,10,8,10,11,12,14,13,12,15,14,16,17,18,16,18,19,16,19,20]);g.computeVertexNormals();return g;}
function pairedEyes(){const s=new THREE.SphereGeometry(.009,7,5),p=s.getAttribute('position') as THREE.BufferAttribute,a:number[]=[],i:number[]=[];for(const sign of [-1,1]){const o=a.length/3;for(let k=0;k<p.count;k++)a.push(p.getX(k)+sign*.055,p.getY(k),p.getZ(k)-.35);for(const index of s.index!.array)i.push(Number(index)+o);}s.dispose();const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(a,3));g.setIndex(i);g.computeVertexNormals();return g;}
function makeStripes(count:number,phases:Float32Array,lengths:Float32Array){const p:number[]=[],i:number[]=[];let base=0;for(const sign of [-1,1])for(const y of [.035,-.005]){for(let k=0;k<=18;k++){const s=.10+k/18*.76,z=-.5+s*.88,profile=Math.pow(Math.sin(Math.PI*s),.62)*(s>.84?Math.max(0,(1-s)/.16):1),x=sign*.060*profile;p.push(x,y-.006,z,x,y+.006,z);}for(let k=0;k<18;k++){const a=base+k*2;i.push(a,a+2,a+1,a+1,a+2,a+3);}base+=38;}const g=new THREE.BufferGeometry(),gold=new THREE.Color('#b99c51'),colors=new Float32Array(p.length);for(let k=0;k<p.length/3;k++)colors.set([gold.r,gold.g,gold.b],k*3);g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.setIndex(i);g.computeVertexNormals();const mesh=new THREE.InstancedMesh(g,animatedStandard('#b99c51','#b99c51'),count);mesh.name='FUSILIER_FINE_GOLD_BANDS';return mesh;}
