/** Pure, metre-based rectangular-drain geometry for runtime and studio tooling. */
export type DrainGeometryConfig={schemaVersion:number;units:string;corridor:{minX:number;maxX:number;centerX:number};primaryOpening:{minX:number;maxX:number;minZ:number;maxZ:number;roofY:number};grate:{frame:number;slatWidth:number;braceWidth:number;slatCount:number;braceCount:number;centerY:number;depth:number;edgeInset:number;rainInset:number}};
export type DrainOpening={minX:number;maxX:number;minZ:number;maxZ:number;roofY:number;frame:number;edgeInset:number;rainInset:number;slatWidth:number;braceWidth:number};
const spaced=(low:number,high:number,count:number)=>Array.from({length:count},(_,index)=>low+(index+1)*(high-low)/(count+1));
const finite=(value:number)=>Number.isFinite(value);
export function createDrainGeometry(config:DrainGeometryConfig){
 const {corridor,primaryOpening,grate}=config;
 if(config.schemaVersion!==1||config.units!=='metres'||!Object.values({...corridor,...primaryOpening,...grate}).every(value=>typeof value==='number'&&finite(value)))throw new Error('Unsupported or non-finite drain geometry config');
 if(corridor.minX>=corridor.maxX||corridor.centerX<=corridor.minX||corridor.centerX>=corridor.maxX||primaryOpening.minX>=primaryOpening.maxX||primaryOpening.minZ>=primaryOpening.maxZ||primaryOpening.roofY<=0)throw new Error('Invalid drain extent');
 if(!Number.isInteger(grate.slatCount)||!Number.isInteger(grate.braceCount)||grate.slatCount<1||grate.braceCount<1||grate.frame<=0||grate.edgeInset<grate.frame||grate.rainInset<=0||grate.slatWidth<=0||grate.braceWidth<=0||grate.depth<=0)throw new Error('Invalid drain grate dimensions');
 const opening:DrainOpening={...primaryOpening,frame:grate.frame,edgeInset:grate.edgeInset,rainInset:grate.rainInset,slatWidth:grate.slatWidth,braceWidth:grate.braceWidth};
 if(opening.minX<corridor.centerX||opening.maxX>corridor.maxX||2*opening.frame>=Math.min(opening.maxX-opening.minX,opening.maxZ-opening.minZ))throw new Error('Drain opening falls outside corridor or is consumed by its frame');
 const slats=spaced(opening.minX+opening.edgeInset,opening.maxX-opening.edgeInset,grate.slatCount),braces=spaced(opening.minZ+opening.edgeInset,opening.maxZ-opening.edgeInset,grate.braceCount);
 const secondary={...opening,minX:2*corridor.centerX-opening.maxX,maxX:2*corridor.centerX-opening.minX};
 const isOpen=(x:number,z:number)=>{if(!finite(x)||!finite(z))return false;const mirrored=x<corridor.centerX?2*corridor.centerX-x:x;return mirrored>opening.minX+opening.frame&&mirrored<opening.maxX-opening.frame&&z>opening.minZ+opening.frame&&z<opening.maxZ-opening.frame&&slats.every(value=>Math.abs(mirrored-value)>opening.slatWidth/2)&&braces.every(value=>Math.abs(z-value)>opening.braceWidth/2);};
 const rainOrigin=(u:number,v:number)=>{const columns=slats.length+1,rows=braces.length+1,safeU=Math.min(1-Number.EPSILON,Math.max(0,finite(u)?u:0)),safeV=Math.min(1-Number.EPSILON,Math.max(0,finite(v)?v:0)),column=Math.floor(safeU*columns),row=Math.floor(safeV*rows),x0=column===0?opening.minX+opening.frame:slats[column-1]+opening.slatWidth/2,x1=column===columns-1?opening.maxX-opening.frame:slats[column]-opening.slatWidth/2,z0=row===0?opening.minZ+opening.frame:braces[row-1]+opening.braceWidth/2,z1=row===rows-1?opening.maxZ-opening.frame:braces[row]-opening.braceWidth/2;if(x1-x0<=2*opening.rainInset||z1-z0<=2*opening.rainInset)throw new Error('Drain rain inset consumes an open grate cell');return {x:x0+opening.rainInset+(x1-x0-2*opening.rainInset)*(safeU*columns-column),z:z0+opening.rainInset+(z1-z0-2*opening.rainInset)*(safeV*rows-row)};};
 return {corridor,opening,secondary,slats,braces,secondarySlats:slats.map(value=>2*corridor.centerX-value).sort((a,b)=>a-b),isOpen,rainOrigin};
}
