import * as T from 'three';import {writeFileSync} from 'node:fs';
import {ArcadeAnimalMotion,profiles} from '../src/places/last-arcade/biology/Motion.ts';
import {arcadeObstacles} from '../src/places/last-arcade/biology/Obstacles.ts';
import {createMantaModel} from '../src/creatures/manta/index.ts';
import {createWhaleSharkModel} from '../src/creatures/whale-shark/index.ts';
const duration=Number(process.argv[3] ?? 600);
const models=[...profiles.slice(0,3).map(p=>createMantaModel(p.size,p.seed)),createWhaleSharkModel(8.5,9140)],motion=new ArcadeAnimalMotion(),obstacles=arcadeObstacles().map(o=>({...o,box:new T.Box3(new T.Vector3(...o.min),new T.Vector3(...o.max))}));
const samples=[],contacts=[],ranges=profiles.map(p=>({id:p.id,minSpeed:Infinity,maxSpeed:0,minHeight:Infinity,maxHeight:0,minRadius:Infinity,maxBank:0,glideSeconds:0,lowSeconds:0})),p=new T.Vector3();
for(let t=0;t<=duration;t+=.5){motion.advance(t);const states=motion.states;states.forEach((s,i)=>{const m=models[i],a=ranges[i];a.minSpeed=Math.min(a.minSpeed,s.velocity.length());a.maxSpeed=Math.max(a.maxSpeed,s.velocity.length());a.minHeight=Math.min(a.minHeight,s.position.y);a.maxHeight=Math.max(a.maxHeight,s.position.y);a.minRadius=Math.min(a.minRadius,1/Math.max(1e-8,Math.abs(s.curvature)));a.maxBank=Math.max(a.maxBank,Math.abs(s.bank)*180/Math.PI);a.glideSeconds+=s.glide>.5?.5:0;a.lowSeconds+=s.state==='LOW_PASS'?.5:0;m.root.position.copy(s.position);m.root.quaternion.copy(s.quaternion);m.update({phase:s.phase,amplitude:1,glide:s.glide,asymmetry:s.asymmetry});m.root.updateMatrixWorld(true);
 m.root.traverse(o=>{if(!(o instanceof T.Mesh))return;const box=new T.Box3().setFromObject(o),near=obstacles.filter(b=>box.intersectsBox(b.box));if(!near.length)return;const positions=o.geometry.getAttribute('position');for(let v=0;v<positions.count;v++){p.fromBufferAttribute(positions,v).applyMatrix4(o.matrixWorld);for(const obstacle of near)if(obstacle.box.containsPoint(p)&&contacts.length<100)contacts.push({time:t,animal:s.id,mesh:o.name,obstacle:obstacle.name,point:p.toArray()});}});
 });if(t%1===0)samples.push(motion.debug());}
const report={durationSeconds:duration,geometrySampleStep:.5,seed:91526,ranges,contacts,events:motion.events,samples,limitations:'Conservative architecture proxy boxes; sampled vertices are not continuous triangle-triangle collision proof.'};writeFileSync(process.argv[2] ?? 'exports/last-arcade-biology/geometry-motion-audit.json',JSON.stringify(report,null,2));models.forEach(m=>m.dispose());console.log(JSON.stringify({ranges,contacts:contacts.length,examples:contacts.slice(0,3)},null,2));if(contacts.length)process.exitCode=1;
